# Generated by Django 3.2.7 on 2021-09-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='areas_intervencao',
            field=models.CharField(choices=[('A1', 'AREA 1'), ('A2', 'AREA 2'), ('A3', 'AREA 3'), ('A4', 'AREA 4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='distrito_escola',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='n_participantes',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4'), ('6', '6'), ('3', '3'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
    ]
