# Generated by Django 3.2.7 on 2021-09-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20210913_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='anexos',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='areas_intervencao',
            field=models.CharField(choices=[('A2', 'AREA 2'), ('A1', 'AREA 1'), ('A4', 'AREA 4'), ('A3', 'AREA 3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='desc_det_proj',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='distrito_escola',
            field=models.CharField(choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='fotografia_passe',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='n_participantes',
            field=models.CharField(choices=[('6', '6'), ('2', '2'), ('4', '4'), ('3', '3'), ('5', '5'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='resumo_uma_pagina',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
