# Generated by Django 3.2.7 on 2021-09-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20210913_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='anexos',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='areas_intervencao',
            field=models.CharField(choices=[('A3', 'AREA 3'), ('A2', 'AREA 2'), ('A4', 'AREA 4'), ('A1', 'AREA 1')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='desc_det_proj',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='distrito_escola',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='fotografia_passe',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='n_participantes',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('6', '6'), ('2', '2'), ('1', '1'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='resumo_uma_pagina',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
