# Generated by Django 3.2.7 on 2021-09-26 15:06

import django.core.files.storage
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_auto_20210913_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='anexos',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='uploads'), upload_to='', verbose_name='Anexos'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='ano_frequenta',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ano que Frequenta'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='areas_intervencao',
            field=models.CharField(blank=True, choices=[('A2', 'AREA 2'), ('A3', 'AREA 3'), ('A1', 'AREA 1'), ('A4', 'AREA 4')], max_length=2, verbose_name='Áreas de Intervenção'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='carreira_seguir',
            field=models.CharField(blank=True, max_length=50, verbose_name='Carreira a Seguir'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=30, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='desc_det_proj',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='uploads'), upload_to='', verbose_name='Descrição Detalhada do Projeto'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='distrito_escola',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=1, verbose_name='Distrito da Escola'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email_prof_coordenador',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Professor Coordenador'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='escola_frequenta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Escola/Universidade que Frequenta'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='fotografia_passe',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='uploads'), upload_to='', verbose_name='Fotografia do Passe'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='localidade',
            field=models.CharField(blank=True, max_length=40, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='localidade_escola',
            field=models.CharField(blank=True, max_length=50, verbose_name='Localidade da Escola'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='morada_completa',
            field=models.CharField(blank=True, max_length=30, verbose_name='Morada Completa'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='n_cartao_cidadao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº do Cartão Cidadão'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='n_id_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº do Id Fiscal'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='n_participantes',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('5', '5'), ('6', '6'), ('3', '3'), ('1', '1')], max_length=1, verbose_name='Nº de Participantes'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='pais',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='passatempo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Passatempo'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='prof_coordenador',
            field=models.CharField(blank=True, max_length=50, verbose_name='Professor Coordenador'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='resumo_trabalho',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Resumo do Trabalho'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='resumo_uma_pagina',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='uploads'), upload_to='', verbose_name='Resumo de 1 Página'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telemovel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telemovel'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='termos_privacidade',
            field=models.BooleanField(default=False, verbose_name='Li  Li e Concordo com os Termos de Privacidade'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='titulo_trabalho',
            field=models.CharField(blank=True, max_length=40, verbose_name='Titulo do Trabalho'),
        ),
    ]
