# Generated by Django 3.2.7 on 2021-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_auto_20210926_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='areas_intervencao',
            field=models.CharField(choices=[('A3', 'AREA 3'), ('A1', 'AREA 1'), ('A2', 'AREA 2'), ('A4', 'AREA 4')], max_length=2, verbose_name='Áreas de Intervenção'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='distrito_escola',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Distrito da Escola'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='n_participantes',
            field=models.CharField(blank=True, choices=[('6', '6'), ('5', '5'), ('2', '2'), ('4', '4'), ('3', '3'), ('1', '1')], max_length=1, verbose_name='Nº de Participantes'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='titulo_trabalho',
            field=models.CharField(max_length=40, verbose_name='Titulo do Trabalho'),
        ),
    ]
